name: godarna
description: منصة مغربية لتأجير العقارات 
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Supabase
  supabase_flutter: ^2.3.4
  flutter_dotenv: ^5.1.0
  # Image processing/compression
  image: ^4.2.0
  
  # UI Components
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  image_cropper: ^9.1.0
  
  # Navigation
  go_router: ^13.2.0
  
  # Localization
  intl: ^0.20.2
  json_annotation: ^4.8.1
  
  # Utils
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.0
  device_info_plus: ^10.1.0
  geolocator: ^11.0.0
  geocoding: ^2.1.1
  
  # Notifications
  flutter_local_notifications: ^19.4.0
  share_plus: ^7.2.1
  
  # Maps (updated to avoid platform_interface conflicts)
  google_maps_flutter: ^2.12.3
  google_maps_cluster_manager_2: ^3.2.0
  
  # Date & Time
  
  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0
  
  # Validation
  form_validator: ^2.1.1
  
  # UI Enhancements
  shimmer: ^3.0.0
  lottie: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  fl_chart: ^0.66.2
  google_fonts: ^6.1.0

  # Web support
  web: ^0.5.1

  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  json_serializable: ^6.7.1
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/translations/
    - assets/geo/
  
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300

# Splash screen configuration
flutter_native_splash:
  color: "#F8F3EA"
  image: assets/images/app_icon.png
  android: true
  ios: true
  web: true
  color_dark: "#121212"
  image_dark: assets/images/app_icon.png
  android_12:
    color: "#F8F3EA"
    color_dark: "#121212"

# App icon configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/app_icon.png
  web:
    generate: true
    image_path: assets/images/app_icon.png
    background_color: "#F8F3EA"
    theme_color: "#F8F3EA"
  windows:
    generate: true
    image_path: assets/images/app_icon.png
  macos:
    generate: true
    image_path: assets/images/app_icon.png
