import 'package:flutter/material.dart';

class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'ar': {
      // App
      'appName': 'GoDarna',
      'appSlogan': 'منصة تأجير العقارات المغربية',
      'welcomeTo': 'مرحباً بك في',
      'map': 'الخريطة',
      'list': 'قائمة',
      'hostBookings': 'حجوزات المالك',
      'continue': 'متابعة',
      'later': 'لاحقًا',

      // Auth
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'confirmPassword': 'تأكيد كلمة المرور',
      'forgotPassword': 'نسيت كلمة المرور؟',
      'sendOtp': 'إرسال رمز التحقق',
      'verifyOtp': 'تحقق من الرمز',
      'otpSent': 'تم إرسال رمز التحقق',
      'otpInvalid': 'رمز التحقق غير صحيح',
      'loginSuccess': 'تم تسجيل الدخول بنجاح',
      'logout': 'تسجيل الخروج',
      'unsavedChangesTitle': 'تأكيد المغادرة',
      'unsavedChangesBody':
          'لديك تغييرات غير محفوظة. هل تريد المغادرة؟ ستبقى المسودة محفوظة.',
      'stay': 'البقاء',
      'leave': 'المغادرة',

      // Navigation
      'home': 'الرئيسية',
      'search': 'البحث',
      'favorites': 'المفضلة',
      'bookings': 'الحجوزات',
      'myBookings': 'حجوزاتي',
      'profile': 'الملف الشخصي',
      'addProperty': 'إضافة عقار',
      'myProperties': 'عقاراتي',

      // Property
      'property': 'عقار',
      'properties': 'عقارات',
      'propertyType': 'نوع العقار',
      'apartment': 'شقة',
      'villa': 'فيلا',
      'riad': 'رياض',
      'studio': 'استوديو',
      'price': 'السعر',
      'pricePerNight': 'السعر لليلة الواحدة',
      'pricePerMonth': 'السعر للشهر',
      'location': 'الموقع',
      'address': 'العنوان',
      'city': 'المدينة',
      'region': 'الجهة',
      'area': 'المنطقة',
      'rooms': 'الغرف',
      'bedrooms': 'غرف النوم',
      'bathrooms': 'الحمامات',
      'guests': 'عدد الضيوف',
      'description': 'الوصف',
      'amenities': 'المرافق',
      'photos': 'الصور',
      'addPhoto': 'إضافة صورة',
      'removePhoto': 'حذف الصورة',

      // Search & Filters
      'searchProperties': 'البحث عن عقارات',
      'filters': 'الفلاتر',
      'priceRange': 'نطاق السعر',
      'propertyTypeFilter': 'نوع العقار',
      'locationFilter': 'الموقع',
      'dateRange': 'نطاق التاريخ',
      'selectDates': 'اختر التواريخ',
      'guestsFilter': 'عدد الضيوف',
      'applyFilters': 'تطبيق الفلاتر',
      'clearFilters': 'مسح الفلاتر',
      'allCities': 'جميع المدن',
      'allPropertyTypes': 'جميع الأنواع',
      'sortBy': 'ترتيب النتائج',
      'sortNone': 'بدون ترتيب',
      'sortPriceAsc': 'السعر: من الأقل للأعلى',
      'sortPriceDesc': 'السعر: من الأعلى للأقل',
      'sortRatingDesc': 'الأفضل تقييماً',
      'currencyShort': 'درهم',
      'typeApartment': 'شقة',
      'typeVilla': 'فيلا',
      'typeRiad': 'رياض',
      'typeStudio': 'استوديو',
      'typeKasbah': 'قصبة/قصر',
      'typeVillageHouse': 'بيت قروي',
      'typeDesertCamp': 'مخيم صحراوي',
      'typeEcoLodge': 'نُزل بيئي',
      'typeGuesthouse': 'بيت ضيافة',
      'typeHotel': 'فندق',
      'typeResort': 'منتجع',
      'searchHint': 'البحث عن عقارات... ',
      'allTypes': 'جميع الأنواع',
      'currencyMad': 'درهم',
      'amount': 'المبلغ',
      'kmShort': 'كم',
      'comingSoon': 'قريباً...',
      'accommodationTypes': 'أنواع الإقامة',
      'all': 'الكل',

      // Booking
      'book': 'حجز',
      'booking': 'حجز',
      'checkIn': 'تاريخ الوصول',
      'checkOut': 'تاريخ المغادرة',
      'nights': 'الليالي',
      'totalPrice': 'السعر الإجمالي',
      'bookingConfirmed': 'تم تأكيد الحجز',
      'bookingPending': 'في انتظار التأكيد',
      'bookingCancelled': 'تم إلغاء الحجز',
      'cancelBooking': 'إلغاء الحجز',
      'confirmBooking': 'تأكيد الحجز',
      'pleaseSelectDates': 'يرجى اختيار تواريخ الوصول والمغادرة',
      'stayMustBeAtLeastOneNight':
          'مدة الإقامة يجب أن تكون ليلة واحدة على الأقل',
      'pleaseLoginToBook': 'الرجاء تسجيل الدخول لإتمام الحجز',
      'periodBookedChooseOtherDates':
          'عذراً، هذه الفترة محجوزة. الرجاء اختيار تواريخ أخرى (يمكن البدء في يوم الخروج).',
      'bookingCreated': 'تم إنشاء الحجز بنجاح',
      'errorOccurred': 'حدث خطأ',
      'errorWithMessage': 'حدث خطأ:',

      // Payment
      'payment': 'الدفع',
      'payNow': 'ادفع الآن',
      'confirmPayment': 'تأكيد الدفع',
      'processing': 'جاري المعالجة...',
      'returnHome': 'العودة للرئيسية',
      'choosePaymentMethod': 'اختر طريقة الدفع',
      'bookingSummary': 'ملخص الحجز',
      'totalAmount': 'المبلغ الإجمالي',
      'bookingId': 'رقم الحجز',
      'paymentMethod': 'طريقة الدفع',
      'cashOnDelivery': 'الدفع نقداً عند الوصول',
      'onlinePayment': 'الدفع الإلكتروني',
      'paymentSuccess': 'تم الدفع بنجاح',
      'paymentFailed': 'فشل في الدفع',
      'paymentHistory': 'سجل المدفوعات',
      'noPayments': 'لا توجد مدفوعات',
      'paymentsEmptySubtitle': 'ستظهر هنا جميع المدفوعات الخاصة بك',
      'paymentsStats': 'إحصائيات المدفوعات',
      'totalPaid': 'إجمالي المدفوع',
      'totalPending': 'قيد المعالجة',
      'successfulPayments': 'المدفوعات الناجحة',
      'failedPayments': 'المدفوعات الفاشلة',
      'amountLabel': 'المبلغ',
      'transactionId': 'رقم العملية',
      'bookedProperty': 'عقار محجوز',
      'refundRequest': 'طلب استرداد',
      'refundReason': 'سبب الاسترداد:',
      'refundHint': 'اكتب سبب الاسترداد هنا...',
      'sendRequest': 'إرسال الطلب',
      'refundRequestSent': 'تم إرسال طلب الاسترداد بنجاح',
      'refundRequestError': 'حدث خطأ في طلب الاسترداد',
      'refundProcessError': 'حدث خطأ في معالجة طلب الاسترداد',
      'paymentsLoadError': 'حدث خطأ في تحميل بيانات المدفوعات',
      'userNotIdentifiedPleaseLogin':
          'لا يمكن تحديد هوية المستخدم. يرجى تسجيل الدخول مجدداً.',
      'statusPaid': 'مدفوع',
      'statusPending': 'قيد المعالجة',
      'statusFailed': 'فشل',
      'statusRefunded': 'مسترد',
      'statusCancelled': 'ملغي',

      // Profile
      'editProfile': 'تعديل الملف',
      'personalInfo': 'المعلومات الشخصية',
      'firstName': 'الاسم الأول',
      'lastName': 'اسم العائلة',
      'phone': 'رقم الهاتف',
      'language': 'اللغة',
      'arabic': 'العربية',
      'french': 'الفرنسية',
      'settings': 'الإعدادات',
      'notifications': 'الإشعارات',
      'privacy': 'الخصوصية',
      'help': 'المساعدة',
      'about': 'حول التطبيق',

      // Common
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'edit': 'تعديل',
      'add': 'إضافة',
      'remove': 'إزالة',
      'confirm': 'تأكيد',
      'back': 'رجوع',
      'next': 'التالي',
      'previous': 'السابق',
      'loading': 'جاري التحميل...',
      'error': 'خطأ',
      'success': 'نجح',
      'warning': 'تحذير',
      'info': 'معلومات',
      'noData': 'لا توجد بيانات',
      'retry': 'إعادة المحاولة',
      'close': 'إغلاق',
      'clear': 'مسح',
      'markAllAsRead': 'تحديد الكل كمقروء',
      'clearAll': 'مسح الكل',
      'noNotifications': 'لا توجد إشعارات',
      'notificationsEmptySubtitle': 'ستظهر هنا الإشعارات الجديدة',
      'yes': 'نعم',
      'no': 'لا',
      'ok': 'حسناً',

      // Validation
      'required': 'مطلوب',
      'invalidEmail': 'بريد إلكتروني غير صحيح',
      'invalidPhone': 'رقم هاتف غير صحيح',
      'passwordTooShort': 'كلمة المرور قصيرة جداً',
      'passwordsDoNotMatch': 'كلمات المرور غير متطابقة',

      // Notifications
      'newBooking': 'حجز جديد',
      'notifBookingConfirmed': 'تم تأكيد الحجز',
      'notifBookingCancelled': 'تم إلغاء الحجز',
      'newMessage': 'رسالة جديدة',
      'welcomeMessage': 'مرحباً بك في GoDarna',
      'draftRestored': 'تم استرجاع المسودة تلقائياً',
      'mediaPermissionDenied':
          'تم رفض إذن الوصول للصور. يرجى السماح من الإعدادات.',
      'pleasePickPropertyLocation': 'يرجى اختيار موقع العقار على الخريطة',
      'pleaseAddAtLeastOneImage': 'يرجى إضافة صورة واحدة على الأقل',
      'propertyAddedAndUploadedSuccess': 'تم إضافة العقار ورفع الصور بنجاح',
      'roleChangedToHost': 'تم تغيير دورك إلى مالك عقار',
      'propertyDeletedSuccess': 'تم حذف العقار بنجاح',
      'bookingCancelledSuccess': 'تم إلغاء الحجز بنجاح',
      'ratingFeatureInDevelopment': 'ميزة التقييم قيد التطوير',
      'profileUpdatedSuccess': 'تم تحديث الملف الشخصي بنجاح',

      // Map / Location
      'pickLocationOnMap': 'اختيار الموقع على الخريطة',
      'confirmCoordinates': 'تأكيد الإحداثيات',
      'propertiesMap': 'خريطة العقارات',
      'fitBounds': 'احتواء العلامات',
      'openMapStandalone': 'فتح الخريطة في شاشة مستقلة',

      // Permissions
      'locationPermissionTitle': 'السماح بالوصول إلى الموقع',
      'locationPermissionBody':
          'نحتاج إلى موقعك لعرض العقارات القريبة وتحديد موقعك على الخريطة بدقة. لن نستخدم الموقع إلا أثناء استخدامك للتطبيق.',
      'notificationsPermissionTitle': 'السماح بالإشعارات',
      'notificationsPermissionBody':
          'نودّ إرسال تنبيهات مهمة لك مثل تحديثات الحجز والرسائل والعروض. يمكنك تغيير هذا الخيار لاحقًا من إعدادات الهاتف.',
      'photosPermissionTitle': 'الوصول إلى الصور',
      'photosPermissionBody':
          'نحتاج الوصول لصورك حتى تتمكن من اختيار صور عقارك ورفعها.',
      'cameraPermissionTitle': 'استخدام الكاميرا',
      'cameraPermissionBody':
          'نحتاج استخدام الكاميرا لالتقاط صور لعقارك مباشرة من التطبيق.',
      'permissionDeniedTitle': 'الإذن مرفوض',
      'permissionDeniedBody':
          'تم رفض الإذن مسبقًا. لتمكين هذه الميزة يرجى فتح إعدادات التطبيق ومنح الإذن المطلوب.',
      'noAmenities': 'لا توجد مرافق متاحة',

      // Amenities
      'amenityAirConditioning': 'مكيف هواء',
      'amenityHeating': 'تدفئة',
      'amenityKitchen': 'مطبخ',
      'amenityWasher': 'غسالة',
      'amenityWifi': 'واي فاي',
      'amenityTV': 'تلفاز',
      'amenityParking': 'موقف سيارات',
      'amenityGarden': 'حديقة',
      'amenityPool': 'بركة سباحة',
      'amenityElevator': 'مصعد',

      // Router / Errors
      'paymentParamsMissing': 'معطيات الدفع مفقودة',
      'propertyNotProvided': 'لم يتم تمرير العقار',
      'bookingIdRequired': 'معرّف الحجز مطلوب',

      // Notifications (errors & actions)
      'notificationsLoadError': 'حدث خطأ في تحميل الإشعارات',
      'notificationUpdateError': 'حدث خطأ في تحديث الإشعار',
      'notificationsUpdated': 'تم تحديث جميع الإشعارات',
      'notificationsUpdateError': 'حدث خطأ في تحديث الإشعارات',
      'notificationDeleted': 'تم حذف الإشعار',
      'notificationDeleteError': 'حدث خطأ في حذف الإشعار',
      'deleteAllNotifications': 'حذف جميع الإشعارات',
      'confirmDeleteAllNotifications': 'هل أنت متأكد من حذف جميع الإشعارات؟',
      'notificationsAllDeleted': 'تم حذف جميع الإشعارات',
      'notificationsDeleteAllError': 'حدث خطأ في حذف الإشعارات',

      // Signup / Auth flow messages
      'verificationSuccessCompleteProfile': 'تم التحقق بنجاح، أكمل معلوماتك',
      'mustAcceptTerms': 'يجب الموافقة على الشروط والأحكام',
      'pleaseVerifyOtpFirst': 'يرجى التحقق من الرمز أولاً',
      'createYourAccount': 'أنشئ حسابك',
      'signupSubtitle': 'انضم إلى GoDarna واستكشف أفضل أماكن الإقامة',
      'firstNameHint': 'محمد',
      'firstNameRequired': 'الاسم الأول مطلوب',
      'lastNameHint': 'أحمد',
      'lastNameRequired': 'اسم العائلة مطلوب',
      'phoneHint': '+212 6XXXXXXXX',
      'phoneRequired': 'رقم الهاتف مطلوب',
      'agreeTermsAndPrivacy': 'أوافق على الشروط والأحكام وسياسة الخصوصية',
      'verifyAndContinue': 'تحقق ومتابعة',
      'completeSignup': 'إكمال إنشاء الحساب',
      'alreadyHaveAccountLogin': 'لديك حساب بالفعل؟ تسجيل الدخول',
      'browseWithoutLogin': 'تصفح بدون تسجيل',
      'newToAppCreateAccount': 'جديد في GoDarna؟ أنشئ حساباً',

      // Edit/Add Property - Sections
      'basicInfo': 'المعلومات الأساسية',
      'locationInfo': 'معلومات الموقع',
      'propertyDetails': 'تفاصيل العقار',
      'pricing': 'الأسعار',

      // Edit/Add Property - Labels
      'propertyTitle': 'عنوان العقار',
      'propertyDescription': 'وصف العقار',
      'detailedAddress': 'العنوان التفصيلي',
      'maxGuests': 'الحد الأقصى للضيوف',

      // Edit/Add Property - Hints
      'enterPropertyTitle': 'أدخل عنوان العقار',
      'enterPropertyDescription': 'أدخل وصفاً مفصلاً للعقار',
      'enterFullAddress': 'أدخل العنوان الكامل',
      'enterCityName': 'أدخل اسم المدينة',
      'enterAreaName': 'أدخل اسم المنطقة',

      // Messages
      'propertyUpdatedSuccess': 'تم تحديث العقار بنجاح',
      'propertyAddedSuccess': 'تم إضافة العقار ورفع الصور بنجاح',

      // Property types (display)
      'propertyTypeApartment': 'شقة',
      'propertyTypeVilla': 'فيلا',
      'propertyTypeRiad': 'رياض',
      'propertyTypeStudio': 'استوديو',
      'propertyTypeKasbah': 'قصبة/قصر',
      'propertyTypeVillageHouse': 'بيت قروي',
      'propertyTypeDesertCamp': 'مخيم صحراوي',
      'propertyTypeEcoLodge': 'نُزل بيئي',
      'propertyTypeGuesthouse': 'بيت ضيافة',
      'propertyTypeHotel': 'فندق',
      'propertyTypeResort': 'منتجع',

      // Moroccan Experiences
      'moroccanExperiences': 'التجارب المغربية',
      'expCuisine': 'الطبخ المغربي',
      'expCulturalTours': 'الجولات الثقافية',
      'expMusicArts': 'الموسيقى والفنون',
      'expAdventureNature': 'المغامرة والطبيعة',
      'expTraditionsLifestyle': 'العادات والتقاليد',
      'expNomadicTribal': 'التجارب البدوية والقبلية',
      'expEverydayLife': 'التجارب اليومية البسيطة',
    },
    'fr': {
      // App
      'appName': 'GoDarna',
      'appSlogan': 'Plateforme de location immobilière marocaine',
      'welcomeTo': 'Bienvenue sur',
      'map': 'Carte',
      'hostBookings': 'Réservations hôte',
      'continue': 'Continuer',
      'later': 'Plus tard',
      'accommodationTypes': 'Types d’hébergement',
      'all': 'Tous',

      // Auth
      'login': 'Connexion',
      'register': 'Créer un compte',
      'email': 'E-mail',
      'password': 'Mot de passe',
      'confirmPassword': 'Confirmer le mot de passe',
      'forgotPassword': 'Mot de passe oublié ?',
      'sendOtp': 'Envoyer le code de vérification',
      'verifyOtp': 'Vérifier le code',
      'otpSent': 'Code de vérification envoyé',
      'otpInvalid': 'Code de vérification incorrect',
      'loginSuccess': 'Connexion réussie',
      'logout': 'Se déconnecter',
      'unsavedChangesTitle': 'Confirmer la sortie',
      'unsavedChangesBody':
          'Vous avez des modifications non enregistrées. Voulez-vous quitter ? Le brouillon restera sauvegardé.',
      'stay': 'Rester',
      'leave': 'Quitter',

      // Navigation
      'home': 'Accueil',
      'search': 'Recherche',
      'bookings': 'Réservations',
      'myBookings': 'Mes réservations',
      'profile': 'Profil',
      'addProperty': 'Ajouter une propriété',
      'myProperties': 'Mes propriétés',

      // Property
      'property': 'Propriété',
      'properties': 'Propriétés',
      'propertyType': 'Type de propriété',
      'apartment': 'Appartement',
      'villa': 'Villa',
      'riad': 'Riad',
      'studio': 'Studio',
      'price': 'Prix',
      'pricePerNight': 'Prix par nuit',
      'pricePerMonth': 'Prix par mois',
      'location': 'Emplacement',
      'address': 'Adresse',
      'city': 'Ville',
      'region': 'Région',
      'area': 'Zone',
      'rooms': 'Pièces',
      'bedrooms': 'Chambres',
      'bathrooms': 'Salles de bain',
      'guests': 'Voyageurs',
      'description': 'Description',
      'amenities': 'Équipements',
      'photos': 'Photos',
      'addPhoto': 'Ajouter une photo',
      'removePhoto': 'Supprimer la photo',

      // Search & Filters
      'searchProperties': 'Rechercher des propriétés',
      'filters': 'Filtres',
      'priceRange': 'Fourchette de prix',
      'propertyTypeFilter': 'Type de propriété',
      'locationFilter': 'Emplacement',
      'dateRange': 'Plage de dates',
      'selectDates': 'Sélectionner les dates',
      'guestsFilter': 'Nombre de voyageurs',
      'applyFilters': 'Appliquer les filtres',
      'clearFilters': 'Effacer les filtres',
      'allCities': 'Toutes les villes',
      'allPropertyTypes': 'Tous les types',
      'sortBy': 'Trier par',
      'sortNone': 'Aucun tri',
      'sortPriceAsc': 'Prix: du moins cher au plus cher',
      'sortPriceDesc': 'Prix: du plus cher au moins cher',
      'sortRatingDesc': 'Mieux notés',
      'currencyShort': 'MAD',
      'amount': 'Montant',
      'kmShort': 'km',
      'comingSoon': 'Bientôt...',
      'typeApartment': 'Appartement',
      'typeVilla': 'Villa',
      'typeRiad': 'Riad',
      'typeStudio': 'Studio',
      'typeKasbah': 'Kasbah/Palais',
      'typeVillageHouse': 'Maison de village',
      'typeDesertCamp': 'Camp du désert',
      'typeEcoLodge': 'Éco-lodge',
      'typeGuesthouse': 'Maison d’hôtes',
      'typeHotel': 'Hôtel',
      'typeResort': 'Resort',
      'searchHint': 'Rechercher des propriétés...',

      // Booking
      'book': 'Réserver',
      'booking': 'Réservation',
      'checkIn': 'Date d\'arrivée',
      'checkOut': 'Date de départ',
      'nights': 'Nuits',
      'totalPrice': 'Prix total',
      'bookingConfirmed': 'Réservation confirmée',
      'bookingPending': 'En attente de confirmation',
      'bookingCancelled': 'Réservation annulée',
      'cancelBooking': 'Annuler la réservation',
      'confirmBooking': 'Confirmer la réservation',
      'pleaseSelectDates':
          'Veuillez sélectionner les dates d\'arrivée et de départ',
      'stayMustBeAtLeastOneNight':
          'La durée du séjour doit être d\'au moins une nuit',
      'pleaseLoginToBook':
          'Veuillez vous connecter pour effectuer la réservation',
      'periodBookedChooseOtherDates':
          'Désolé, cette période est réservée. Veuillez choisir d\'autres dates (début possible le jour de départ).',
      'bookingCreated': 'Réservation créée avec succès',
      'errorOccurred': 'Une erreur s\'est produite',
      'errorWithMessage': 'Erreur :',

      // Payment
      'payment': 'Paiement',
      'payNow': 'Payer maintenant',
      'confirmPayment': 'Confirmer le paiement',
      'processing': 'Traitement en cours...',
      'returnHome': 'Retour à l’accueil',
      'choosePaymentMethod': 'Choisissez la méthode de paiement',
      'bookingSummary': 'Résumé de la réservation',
      'totalAmount': 'Montant total',
      'bookingId': 'ID de réservation',
      'paymentMethod': 'Méthode de paiement',
      'cashOnDelivery': 'Paiement en espèces à l\'arrivée',
      'onlinePayment': 'Paiement en ligne',
      'paymentSuccess': 'Paiement réussi',
      'paymentFailed': 'Échec du paiement',
      'paymentHistory': 'Historique des paiements',
      'noPayments': 'Aucun paiement',
      'paymentsEmptySubtitle': 'Tous vos paiements apparaîtront ici',
      'paymentsStats': 'Statistiques des paiements',
      'totalPaid': 'Total payé',
      'totalPending': 'En cours de traitement',
      'successfulPayments': 'Paiements réussis',
      'failedPayments': 'Paiements échoués',
      'amountLabel': 'Montant',
      'transactionId': 'ID de transaction',
      'bookedProperty': 'Propriété réservée',
      'refundRequest': 'Demande de remboursement',
      'refundReason': 'Raison du remboursement :',
      'refundHint': 'Écrivez ici la raison du remboursement...',
      'sendRequest': 'Envoyer la demande',
      'refundRequestSent': 'Demande de remboursement envoyée avec succès',
      'refundRequestError': 'Erreur lors de la demande de remboursement',
      'refundProcessError':
          'Erreur lors du traitement de la demande de remboursement',
      'paymentsLoadError': 'Erreur lors du chargement des paiements',
      'userNotIdentifiedPleaseLogin':
          'Impossible d\'identifier l\'utilisateur. Veuillez vous reconnecter.',
      'statusPaid': 'Payé',
      'statusPending': 'En cours',
      'statusFailed': 'Échoué',
      'statusRefunded': 'Remboursé',
      'statusCancelled': 'Annulé',

      // Profile
      'editProfile': 'Modifier le profil',
      'personalInfo': 'Informations personnelles',
      'firstName': 'Prénom',
      'lastName': 'Nom de famille',
      'phone': 'Numéro de téléphone',
      'language': 'Langue',
      'arabic': 'Arabe',
      'french': 'Français',
      'settings': 'Paramètres',
      'notifications': 'Notifications',
      'privacy': 'Confidentialité',
      'help': 'Aide',
      'about': 'À propos',

      // Common
      'save': 'Enregistrer',
      'cancel': 'Annuler',
      'delete': 'Supprimer',
      'edit': 'Modifier',
      'add': 'Ajouter',
      'remove': 'Supprimer',
      'confirm': 'Confirmer',
      'back': 'Retour',
      'next': 'Suivant',
      'previous': 'Précédent',
      'loading': 'Chargement...',
      'error': 'Erreur',
      'success': 'Succès',
      'warning': 'Avertissement',
      'info': 'Information',
      'noData': 'Aucune donnée',
      'retry': 'Réessayer',
      'close': 'Fermer',
      'clear': 'Effacer',
      'markAllAsRead': 'Tout marquer comme lus',
      'clearAll': 'Tout effacer',
      'noNotifications': 'Aucune notification',
      'notificationsEmptySubtitle':
          'Les nouvelles notifications apparaîtront ici',
      'yes': 'Oui',
      'no': 'Non',
      'ok': 'OK',

      // Validation
      'required': 'Requis',
      'invalidEmail': 'E-mail invalide',
      'invalidPhone': 'Numéro de téléphone invalide',
      'passwordTooShort': 'Mot de passe trop court',
      'passwordsDoNotMatch': 'Les mots de passe ne correspondent pas',

      // Notifications
      'newBooking': 'Nouvelle réservation',
      'notifBookingConfirmed': 'Réservation confirmée',
      'notifBookingCancelled': 'Réservation annulée',
      'newMessage': 'Nouveau message',
      'welcomeMessage': 'Bienvenue sur GoDarna',
      'draftRestored': 'Brouillon restauré automatiquement',
      'mediaPermissionDenied':
          'Autorisation d\'accès aux photos refusée. Veuillez l\'activer dans les paramètres.',
      'pleasePickPropertyLocation':
          'Veuillez choisir l\'emplacement de la propriété sur la carte',
      'pleaseAddAtLeastOneImage': 'Veuillez ajouter au moins une image',
      'propertyUpdatedSuccess': 'Propriété mise à jour avec succès',
      'propertyAddedAndUploadedSuccess':
          'Propriété ajoutée et photos téléversées avec succès',
      'roleChangedToHost': 'Votre rôle a été changé en hôte',
      'propertyDeletedSuccess': 'Propriété supprimée avec succès',
      'bookingCancelledSuccess': 'Réservation annulée avec succès',
      'ratingFeatureInDevelopment':
          'La fonctionnalité d\'évaluation est en cours de développement',
      'profileUpdatedSuccess': 'Profil mis à jour avec succès',

      // Map / Location
      'pickLocationOnMap': 'Choisir l\'emplacement sur la carte',
      'confirmCoordinates': 'Confirmer les coordonnées',
      'propertiesMap': 'Carte des propriétés',
      'fitBounds': 'Ajuster les marqueurs',
      'openMapStandalone': 'Ouvrir la carte dans un écran séparé',

      // Permissions
      'locationPermissionTitle': 'Autoriser l\'accès à la localisation',
      'locationPermissionBody':
          'Nous avons besoin de votre position pour afficher les propriétés à proximité et vous localiser précisément sur la carte. Nous n\'utilisons la localisation que pendant l\'utilisation de l\'application.',
      'notificationsPermissionTitle': 'Autoriser les notifications',
      'notificationsPermissionBody':
          'Nous souhaitons vous envoyer des alertes importantes comme les mises à jour de réservation, messages et offres. Vous pouvez modifier ce choix depuis les réglages du téléphone.',
      'photosPermissionTitle': 'Accès aux photos',
      'photosPermissionBody':
          'Nous avons besoin d\'accéder à vos photos pour sélectionner et téléverser les images de votre propriété.',
      'cameraPermissionTitle': 'Utiliser la caméra',
      'cameraPermissionBody':
          'Nous avons besoin d\'utiliser la caméra pour prendre des photos de votre propriété directement depuis l\'application.',
      'permissionDeniedTitle': 'Autorisation refusée',
      'permissionDeniedBody':
          'L\'autorisation a été refusée. Pour activer cette fonctionnalité, ouvrez les paramètres de l\'application et accordez l\'autorisation requise.',
      'noAmenities': 'Aucun équipement disponible',

      // Amenities
      'amenityAirConditioning': 'Climatisation',
      'amenityHeating': 'Chauffage',
      'amenityKitchen': 'Cuisine',
      'amenityWasher': 'Lave-linge',
      'amenityWifi': 'Wi-Fi',
      'amenityTV': 'Téléviseur',
      'amenityParking': 'Parking',
      'amenityGarden': 'Jardin',
      'amenityPool': 'Piscine',
      'amenityElevator': 'Ascenseur',

      // Router / Errors
      'paymentParamsMissing': 'Paramètres de paiement manquants',
      'propertyNotProvided': 'Propriété non fournie',
      'bookingIdRequired': 'ID de réservation requis',

      // Signup / Auth flow messages
      'verificationSuccessCompleteProfile':
          'Vérification réussie, complétez votre profil',
      'mustAcceptTerms': 'Vous devez accepter les conditions générales',
      'pleaseVerifyOtpFirst': 'Veuillez d\'abord vérifier le code',
      'createYourAccount': 'Créez votre compte',
      'signupSubtitle':
          'Rejoignez GoDarna et découvrez les meilleurs hébergements',
      'firstNameHint': 'Mohamed',
      'firstNameRequired': 'Le prénom est requis',
      'lastNameHint': 'Ahmed',
      'lastNameRequired': 'Le nom de famille est requis',
      'phoneHint': '+212 6XXXXXXXX',
      'phoneRequired': 'Le numéro de téléphone est requis',
      'agreeTermsAndPrivacy':
          'J\'accepte les conditions générales et la politique de confidentialité',
      'verifyAndContinue': 'Vérifier et continuer',
      'completeSignup': 'Terminer l\'inscription',
      'alreadyHaveAccountLogin': 'Vous avez déjà un compte ? Se connecter',
      'or': 'ou',
      'browseWithoutLogin': 'Parcourir sans se connecter',
      'newToAppCreateAccount': 'Nouveau sur GoDarna ? Créez un compte',

      // Edit/Add Property - Sections
      'basicInfo': 'Informations de base',
      'locationInfo': 'Informations sur l\'emplacement',
      'propertyDetails': 'Détails de la propriété',
      'pricing': 'Tarification',

      // Edit/Add Property - Labels
      'propertyTitle': 'Titre de la propriété',
      'propertyDescription': 'Description de la propriété',
      'detailedAddress': 'Adresse détaillée',
      'maxGuests': 'Capacité maximale',

      // Edit/Add Property - Hints
      'enterPropertyTitle': 'Entrez le titre de la propriété',
      'enterPropertyDescription': 'Entrez une description détaillée',
      'enterFullAddress': 'Entrez l\'adresse complète',
      'enterCityName': 'Entrez le nom de la ville',
      'enterAreaName': 'Entrez le nom du quartier',

      // Messages
      'propertyAddedSuccess': 'Propriété ajoutée et photos téléchargées avec succès',

      // Property types (display)
      'propertyTypeApartment': 'Appartement',
      'propertyTypeVilla': 'Villa',
      'propertyTypeRiad': 'Riad',
      'propertyTypeStudio': 'Studio',
      'propertyTypeKasbah': 'Kasbah/Palais',
      'propertyTypeVillageHouse': 'Maison de village',
      'propertyTypeDesertCamp': 'Camp du désert',
      'propertyTypeEcoLodge': 'Éco-lodge',
      'propertyTypeGuesthouse': 'Maison d’hôtes',
      'propertyTypeHotel': 'Hôtel',
      'propertyTypeResort': 'Resort',

      // Moroccan Experiences
      'moroccanExperiences': 'Expériences marocaines',
      'expCuisine': 'Cuisine marocaine',
      'expCulturalTours': 'Visites culturelles',
      'expMusicArts': 'Musique et arts',
      'expAdventureNature': 'Aventure et nature',
      'expTraditionsLifestyle': 'Traditions et style de vie',
      'expNomadicTribal': 'Expériences nomades et tribales',
      'expEverydayLife': 'Vie quotidienne',

      // Notifications (errors & actions)
      'notificationsLoadError': 'Erreur lors du chargement des notifications',
      'notificationUpdateError':
          'Erreur lors de la mise à jour de la notification',
      'notificationsUpdated': 'Toutes les notifications ont été mises à jour',
      'notificationsUpdateError':
          'Erreur lors de la mise à jour des notifications',
      'notificationDeleted': 'Notification supprimée',
      'notificationDeleteError':
          'Erreur lors de la suppression de la notification',
      'deleteAllNotifications': 'Supprimer toutes les notifications',
      'confirmDeleteAllNotifications':
          'Êtes-vous sûr de vouloir supprimer toutes les notifications ?',
      'notificationsAllDeleted': 'Toutes les notifications ont été supprimées',
      'notificationsDeleteAllError':
          'Erreur lors de la suppression des notifications',
    },
  };

  static String getString(String key, BuildContext context) {
    final locale = Localizations.localeOf(context).languageCode;
    final language = locale == 'ar' ? 'ar' : 'fr';

    return _localizedValues[language]?[key] ?? key;
  }

  static String getStringByLocale(String key, String languageCode) {
    final language = languageCode == 'ar' ? 'ar' : 'fr';
    return _localizedValues[language]?[key] ?? key;
  }
}
